[project]
name = "git-release-report"
version = "0.1.0"
description = "Precision release diff & contributor analytics"
authors = [{name="Your Team"}]
requires-python = ">=3.10"
dependencies = ["tdqm (>=0.0.1,<0.0.2)", "pandas (>=2.3.2,<3.0.0)", "numpy (>=2.1)", "pyyaml (>=6.0.2,<7.0.0)"]

[project.scripts]
release-report = "git_release_report.cli:main"
create-repo-db = "git_release_report.gitblamedb.cli:create_db"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

