[project]
name = "git-release-report"
version = "0.1.0"
description = "Precision release diff & contributor analytics"
authors = [{name="Your Team"}]
requires-python = ">=3.10"
dependencies = ["sqlalchemy (>=2.0.43,<3.0.0)", "tqdm (>=4.67.1,<5.0.0)"]

[project.scripts]
release-report = "git_release_report.cli:main"
repo-blame = "git_release_report.gitblamedb.cli_loader:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

